server:
  port: 8081
spring: 
  mvc:
    pathmatch: 
      matching-strategy: ant-path-matcher
eureka:
  instance:
    instance-id: ${random.value}:${spring.application.name}
  client:
    service-url:
      defaultZone: http://server-eureka:8761/eureka
